config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {registrations: "users/registrations"}

  root :to => "main#index"
  get '/helper/parameterize', to: "helper#parameterize"
  get '/given', to: "main#killin_its_given"
  get '/received', to: "main#killin_its_received"
  resources :killin_its, only: [:create, :edit, :update, :destroy]
  get '/:key/given', to: "main#profile_killin_its_given", as: :profile_given
  get '/:key/received', to: "main#profile_killin_its_received", as: :profile_received
  get '/:key', to: "main#profile", as: :profile
  post '/api/login', to: "api#login", as: :api_login
  post '/api/search', to: "api#search", as: :api_search
  post '/api/my_profile', to: "api#my_profile", as: :api_my_profile
  post '/api/my_given', to: "api#my_given", as: :api_my_given
  post '/api/my_received', to: "api#my_received", as: :api_my_received
  post '/api/user_profile', to: "api#user_profile", as: :api_user_profile
  post '/api/user_given', to: "api#user_given", as: :api_user_given
  post '/api/user_received', to: "api#user_received", as: :api_user_received
  post '/api/create_killin_it', to: "api#create_killin_it", as: :api_create_killlin_it
  post '/api/update_killin_it', to: "api#update_killin_it", as: :api_update_killin_it
  post '/api/destroy_killin_it', to: "api#destroy_killin_it", as: :api_destroy_killin_it
  post '/api/logout', to: "api#logout", as: :api_logout
end

app/controllers/main_controller.rb
class MainController < ApplicationController
    before_filter :authenticate_user!, except: [:index]
    before_filter :find_user_by_key, only: [:profile, :profile_killin_its_given, :profile_killin_its_received]

    def index
        if !params[:search].nil? && !params[:search].empty?
            @users = User.like(params[:search])
        else
            @users = []
        end
    end

    def killin_its_given
        @killin_its = current_user.killin_its_from.order(:created_at => :desc).page(params[:page]).per(20)
    end

    def killin_its_received
        @killin_its = current_user.killin_its_to.order(:created_at => :desc).page(params[:page]).per(20)
    end

    def profile
        @new_killin_it = KillinIt.new
        @new_killin_it.from_user = current_user
        @new_killin_it.to_user = @user
    end

    def profile_killin_its_given
        @killin_its = @user.killin_its_from.order(:created_at => :desc).page(params[:page]).per(20)
    end

    def profile_killin_its_received
        @killin_its = @user.killin_its_to.order(:created_at => :desc).page(params[:page]).per(20)
    end

    private

    def find_user_by_key
        @user = User.find_by_userkey(params[:key])
        if @user.nil?
            render_error :notfound
        end
    end
end

app/helpers/main_helper.rb
module MainHelper
end

app/views/main/_endless_pagination.html.haml
.btn-group.btn-group-justified
  - if objects.last_page?
    = link_to "No more entries", "#", class: "btn btn-default btn-lg"
  - else
    = link_to_next_page(objects, "Next Page", remote: true, class: "btn btn-default btn-lg")

app/views/main/_killin_it.html.haml
.panel.panel-default
  .panel-body.middle-vertical
    %p.flex-child.no-left-margin
      %b You' re killin' it!
      from
      %b= link_to elem.from_user.username, profile_path(elem.from_user.userkey)
      to
      %b= link_to elem.to_user.username, profile_path(elem.to_user.userkey)
      at
      %i= elem.created_at.to_s
    - if elem.from_user == current_user || current_user.admin
      .btn-group.pull-right.flex-child.no-right-margin
        = button_to "Edit", edit_killin_it_path(elem.id), method: :get, class: "btn btn-warning", form_class: "force-inline"
        = button_to "Delete", killin_it_path(elem.id), method: :delete, class: "btn btn-danger", form_class: "force-inline"
  - unless elem.message.nil? || elem.message.empty?
    .panel-footer
      = elem.message

app/views/main/_killin_its_listing.html.haml
- killin_its.each do |ki|
    = render partial: "killin_it", locals: {elem: ki}

app/views/main/_profile_navs.html.haml
%ul.nav.nav-pills.nav-justified
  %li{role: "presentation", class: active == :profile ? "active" : ""}= link_to "Profile", profile_path(@user.userkey)
  %li{role: "presentation", class: active == :killin_its_given ? "active" : ""}= link_to "Killin' Its given", profile_given_path(@user.userkey)
  %li{role: "presentation", class: active == :killin_its_received ? "active" : ""}= link_to "Killin' Its received", profile_received_path(@user.userkey)

app/views/main/_users_list.html.haml
- if users.empty?
  .alert.alert-info= "No users matching your query!"
- else
  .list-group
    - users.each do |u|
      %a{href: profile_path(u.userkey), class: "list-group-item"}
        %h3.list-group-item-heading
          = u.username
          - if !u.firstname.nil? || !u.firstname.empty? || !u.lastname.nil? || !u.lastname.empty?
            %span.text-muted= "(" + u.firstname + " " + u.lastname + ")"
        %p.text-muted.list-group-item-text
          Email:
          = u.email
          , key:
          = u.userkey

app/views/main/index.html.haml
- if current_user.nil?
  .jumbotron
    %h1 Welcome to Killin' It!
    %p This is an application, by which you can tell another user "Dude... you' re killin' it" with an optional message.
    %p
      = link_to "Log in", new_user_session_path, class: "btn btn-primary btn-lg"
      or
      = link_to "Sign up", new_user_registration_path, class: "btn btn-primary btn-lg"
      to start using the application!
- else
  = render partial: "navs", locals: {active: :index}
  %h3 Users
  = form_tag root_path, remote: true, class: "users_search_form", method: :get do |f|
    .row
      .col-md-12
        .form-group
          = text_field_tag :search, params[:search], placeholder: "Search for user by username, key, email, firstname or lastname", class: "form-control", id: "users_search"
    .results
      = render partial: "users_list", locals: {users: @users}

app/views/main/killin_its_given.html.haml
= render partial: "navs", locals: {active: :killin_its_given}
%h3 Killin' Its given by you
- if @killin_its.empty?
  .alert.alert-info= "You have not yet given any Killin' Its to anyone!"
- else
  .infinite_killin_it_listing
    = render partial: "killin_its_listing", locals: {killin_its: @killin_its}
  .endless_pagination
    = render partial: "endless_pagination", locals: {objects: @killin_its}

app/views/main/killin_its_given.js.erb
$("<%= escape_javascript(render(partial: "killin_its_listing", locals: {killin_its: @killin_its})) %>").appendTo($(".infinite_killin_it_listing"));
$(".endless_pagination").html("<%= escape_javascript(render(partial: "endless_pagination", locals: {objects: @killin_its})) %>");

app/views/main/killin_its_received.html.haml
= render partial: "navs", locals: {active: :killin_its_received}
%h3 Killin' Its received by you
- if @killin_its.empty?
  .alert.alert-info= "You have not yet received any Killin' Its from anyone!"
- else
  .infinite_killin_it_listing
    = render partial: "killin_its_listing", locals: {killin_its: @killin_its}
  .endless_pagination
    = render partial: "endless_pagination", locals: {objects: @killin_its}

app/views/main/killin_its_received.js.erb
$("<%= escape_javascript(render(partial: "killin_its_listing", locals: {killin_its: @killin_its})) %>").appendTo($(".infinite_killin_it_listing"));
$(".endless_pagination").html("<%= escape_javascript(render(partial: "endless_pagination", locals: {objects: @killin_its})) %>");

app/views/main/profile.html.haml
- if @user == current_user
  = render partial: "navs", locals: {active: :profile}
- else
  = render partial: "profile_navs", locals: {active: :profile}
%h1
  = @user.username
  - if !@user.firstname.nil? || !@user.firstname.empty? || !@user.lastname.nil? || !@user.lastname.empty?
    %span.text-muted= "(" + @user.firstname + " " + @user.lastname + ")"
%dl.dl-horizontal
  %dt Email
  %dd= @user.email
  %dt Joined
  %dd= @user.created_at
  %dt Killin' Its given
  %dd= @user.killin_its_from.count
  %dt Killin' Its received
  %dd= @user.killin_its_to.count
- if @user == current_user
  = link_to "Edit your profile", edit_user_registration_path
- else
  = form_for @new_killin_it, html: {class: "form-horizontal"} do |f|
    .form-group
      .col-md-6
        = f.hidden_field :to_user_id, value: @user.id
        = f.submit "You' re killin' it!", class: "btn btn-success btn-lg"
    .form-group
      .col-md-6
        = f.text_area :message, rows: 10, cols: 30, placeholder: "Additional message (optional)", class: "form-control"
  = link_to "Back", root_path

app/views/main/profile_killin_its_given.html.haml
= render partial: "profile_navs", locals: {active: :killin_its_given}
%h3= "Killin' Its given by #{@user.username}"
- if @killin_its.empty?
  .alert.alert-info= "#{@user.username} has not yet given any Killin' Its to anyone!"
- else
  .infinite_killin_it_listing
    = render partial: "killin_its_listing", locals: {killin_its: @killin_its}
  .endless_pagination
    = render partial: "endless_pagination", locals: {objects: @killin_its}

app/views/main/profile_killin_its_received.html.haml
= render partial: "profile_navs", locals: {active: :killin_its_received}
%h3= "Killin' Its received by #{@user.username}"
- if @killin_its.empty?
  .alert.alert-info= "#{@user.username} has not yet received any Killin' Its from anyone!"
- else
  .infinite_killin_it_listing
    = render partial: "killin_its_listing", locals: {killin_its: @killin_its}
  .endless_pagination
    = render partial: "endless_pagination", locals: {objects: @killin_its}

app/views/main/profile_killin_its_received.js.erb
$("<%= escape_javascript(render(partial: "killin_its_listing", locals: {killin_its: @killin_its})) %>").appendTo($(".infinite_killin_it_listing"));
$(".endless_pagination").html("<%= escape_javascript(render(partial: "endless_pagination", locals: {objects: @killin_its})) %>");